import json
faqs=[
("What is The Cube Chronicles?","The Cube Chronicles is a fifteen-book middle-grade historical time-travel adventure series by Jeremy Tinder. It follows the Carver family — three siblings and their parents — after the children discover a mysterious nine-sided cube beneath their backyard shed that carries them across the ancient world, one civilization per book.",False,["overview"]),
("How many books are in the series?","There are fifteen books. The series is complete, running in reading order from Book 1 (ancient Egypt) to Book 15 (the culmination of the journey).",False,["series"]),
("Do the books need to be read in order?","We recommend reading in order. Each book is a self-contained adventure to a new time and place, but the family's story, relationships, and running threads — Daniel's yearly \"wisdoms,\" Beckah's record-keeping, the cube's growing pattern — build from book to book, and the emotional payoff is richest in sequence. Book 1 introduces the family, the shed, and the cube, so it is the best place to start.",False,["reading order"]),
("What age group is the series for?","The series is written for middle-grade readers, roughly ages 8 to 12, and is frequently enjoyed as a family read-aloud by younger and older readers alike. The vocabulary is rich and the history is real, which also makes the books useful for classrooms and homeschool.",False,["age"]),
("Is the series appropriate for a family read-aloud?","Yes. The books are family-centered and family-friendly, with no profanity, no romance, and only mild adventure-level peril. They are written to be read aloud across ages, and each book explores discussion-worthy themes about family, work, and character.",False,["parents","read-aloud"]),
("Who is the author?","The series is written by Jeremy Tinder, author of The Cube Chronicles. He writes the Carver family across the ancient world and has said that the foundation of every good story, like the foundation of every good building, is love.",False,["author"]),
("Who are the main characters?","The three Carver siblings — Simeon (a builder), Beckah (the family's record-keeper) and Ellie (the family's singer) — along with their parents, Daniel, a builder and carpenter, and Elizabeth, their Filipina-American mother. Each book also introduces friends and mentors from the civilization the children visit.",False,["characters"]),
("Where and when is the series set?","Each book has a contemporary family frame (beginning in 1986 in the rural Carolinas) and a central adventure in a real ancient civilization. Across the series the children visit Egypt, Greece, the Indus Valley, China, Japan, Sumer, the Andes, the Amazon, the Pacific Northwest coast, Anatolia, Minoan Crete, Aboriginal Australia, the Pacific voyaging world, and the Silk Road.",False,["setting"]),
("Is the history based on real civilizations?","Yes. Every destination is grounded in a real historical culture, and the books weave in accurate detail about how people built, farmed, wrote, healed, traded, navigated, and made music. The one fantastical element is the cube itself.",False,["history","accuracy"]),
("Does the series contain time travel or fantasy?","Yes — a mysterious nine-sided cube transports the children through history. Apart from the cube, the stories stay grounded in realistic historical and family life; there is no magic system, monsters, or spellcasting.",False,["genre","time travel"]),
("Is the series suitable for classrooms or homeschool?","Very much so. Each book pairs an adventure story with a real ancient civilization and its crafts and ideas, and several books include discussion questions, historical notes, and vocabulary. Teachers and homeschool families use the series alongside world-history and geography units.",False,["classroom","education"]),
("What themes does the series explore?","Recurring themes include family, history, faith, craftsmanship and honest work, courage, responsibility, hospitality and generosity, and homecoming. Each book adds one of the father's \"wisdoms\" about building — and about building a life.",False,["themes"]),
("Is the series frightening or violent?","No. There are moments of adventure-level tension — a storm, a river animal, a hard journey — but no graphic violence or gore. A few later books touch gently on grief and loss, always handled with warmth and care.",False,["content","safety"]),
("Does the series contain religious or faith themes?","Yes. The Carver family is a Christian family, and their faith — prayer, Scripture, gratitude, hospitality — is woven naturally into their everyday life and travels. It is presented warmly rather than as instruction, and it deepens the family's reflections on what they learn.",False,["faith"]),
("Is God or \"the Maker\" shown as a character?","No. A guiding, unseen presence the family calls \"the Maker\" is spoken of with reverence throughout the series, but is never depicted, described, or shown as a visible character. The final book keeps that same restraint.",False,["faith","the-maker"]),
("How long are the books?","Lengths vary. The first book is the longest at about 591 print pages, and later books settle into a briefer 165–220 page range. Across all fifteen, the series runs about 3,861 paperback pages.",False,["length"]),
("What will readers learn about history and culture?","Readers encounter how the Great Pyramid was really built, how the Parthenon was raised, how the Indus Valley planned its cities, how bronze was cast in ancient China, how Jōmon potters and Pacific wayfinders worked, how the Andes engineered rope bridges, how the Amazon built living soil, and much more — always through the eyes of children learning a craft.",False,["learning","culture"]),
("Which book should I start with?","Start with Book 1, The Shed, The Cube, and The Sands of Time. It introduces the Carver family, the discovery of the cube, and the first crossing to ancient Egypt, and sets up everything that follows.",False,["reading order","start"]),
("Is the series finished, or are more books coming?","The series is complete at fifteen books, telling a full arc from the first crossing to the journey's center. Each book's ending hints at the next, and Book 15 brings the whole spiral home.",False,["series","status"]),
("Are the books standalone or one continuous story?","Both. Each book is a complete adventure to one destination that can be enjoyed on its own, but together they form a single continuous story about a family growing up and growing closer across fifteen years of travel.",False,["series","structure"]),
("Where can I buy the books?","Purchase links for each book appear on that book's page. Retailer links are configured per book; where a link is still being finalized it is clearly marked as a placeholder until the official store link is available.",False,["buy","retail"]),
("Can my child ask questions about the books on this site?","Yes. Registered and verified readers can submit questions on any book's page. Questions and answers are reviewed by a moderator before they appear publicly, so the community stays safe and on-topic. You never need an account just to read the books' editorial FAQs.",False,["community","questions"]),
("How does the community Q&A work?","Readers can register with a display name and email, verify their email, and then ask questions or post answers and comments on a book's discussion. Everything is moderated before publishing. If you ask a question, you're automatically subscribed to be notified by email when an approved answer is posted, and you can unsubscribe at any time.",False,["community","how-it-works"]),
("How is my email address used?","Your email is used only to verify your account and to send the discussion notifications you've asked for. Email addresses are never displayed publicly or sold, and every notification includes an unsubscribe link. See the Privacy Policy for full details.",False,["privacy","email"]),
]
out=[]
for i,(q,a,sp,tags) in enumerate(faqs,1):
    out.append({"id":f"series-faq{i:02d}","anchor":f"faq-{i:02d}","q":q,"a":a,"spoiler":sp,"tags":tags})
json.dump(out, open("/home/claude/cubechronicles/src/content/series-faqs.json","w"), indent=2, ensure_ascii=False)
print("series-faqs.json written:", len(out), "FAQs")
